add/edit round done
SkillsForge-Community/Sigma-Quiz-UI pull request #64
Opened 2024-06-18 16:48 UTC by SamuelOmodele

2024-06-19 10:11 UTC, a-k-o-r-e-d-e commented
@SamuelOmodele can you please resolve the conflicts so i can merge this in?

2024-06-19 12:24 UTC, SamuelOmodele commented
> @SamuelOmodele can you please resolve the conflicts so i can merge this in?

I've resolved it.

2024-06-19 16:33 UTC, a-k-o-r-e-d-e commented
I can see a conflict

2024-06-19 16:33 UTC, a-k-o-r-e-d-e commented
> > @SamuelOmodele can you please resolve the conflicts so i can merge this in?
> 
> I've resolved it.

i can still see a conflict in the EditQuix.tsx file

2024-06-19 16:43 UTC, a-k-o-r-e-d-e requested changes

2024-06-19 16:43 UTC, a-k-o-r-e-d-e commented on src/Pages/Round/AddEditRound.tsx
date could have been formatted using the date-fns package but we will allow

2024-06-19 20:33 UTC, SamuelOmodele commented on src/Pages/Round/AddEditRound.tsx
Okay sir. 

I have resolved the conflicts. I saw the same conflict when i first created the Pull request and corrected it then, I don't know why it came up again.

2024-06-19 20:44 UTC, SamuelOmodele commented
> > > @SamuelOmodele can you please resolve the conflicts so i can merge this in?
> > 
> > 
> > I've resolved it.
> 
> i can still see a conflict in the EditQuix.tsx file

I have corrected it

2024-06-20 05:45 UTC, a-k-o-r-e-d-e approved these changes

2024-06-20 05:46 UTC, merged