Quizlist
SkillsForge-Community/Sigma-Quiz-UI pull request #68
Opened 2024-06-19 14:00 UTC by demi05

Consumed API for quiz list and added login to home page

2024-06-19 14:01 UTC, silasade submitted a review, later dismissed

2024-06-19 14:06 UTC, silasade submitted a review, later dismissed

2024-06-19 16:14 UTC, a-k-o-r-e-d-e requested changes

2024-06-19 16:14 UTC, a-k-o-r-e-d-e commented on src/Pages/Homepage/Index.tsx
line 79: the error to the user should be user friendly and should just say something like "Error Fetching Quizes. Try Again"

2024-06-19 16:14 UTC, a-k-o-r-e-d-e commented on src/Pages/Signin/Index.tsx
line 45: nothing like 'adhocroles' it is 'adhoc'

2024-06-19 19:50 UTC, demi05 commented on src/Pages/Homepage/Index.tsx
Will change this now

2024-06-20 05:47 UTC, a-k-o-r-e-d-e approved these changes

2024-06-20 05:47 UTC, merged