Component styles
SkillsForge-Community/Sigma-Quiz-UI pull request #73
Opened 2024-06-19 15:54 UTC by demi05

Converted logo styles to chakra

2024-06-19 15:56 UTC, silasade approved these changes

2024-06-19 16:31 UTC, a-k-o-r-e-d-e requested changes

2024-06-19 16:31 UTC, a-k-o-r-e-d-e commented on src/Pages/Homepage/Index.tsx
there is type for the css properties, type loginButtonStyle properly to avoid errors or wrong properties

2024-06-19 16:31 UTC, a-k-o-r-e-d-e commented on src/Global Components/Logo/Logo.tsx
there is type for the css properties, type logoTextStyle1 & logoTextStyle2 properly to avoid errors or wrong properties

2024-06-20 12:17 UTC, demi05 commented on src/Global Components/Logo/Logo.tsx
Done

2024-06-20 12:17 UTC, demi05 commented on src/Pages/Homepage/Index.tsx
Done

2024-06-20 13:24 UTC, a-k-o-r-e-d-e requested changes

2024-06-20 13:24 UTC, a-k-o-r-e-d-e commented on src/Global Components/Logo/Logo.tsx
use the proper type 'React.CSSProperties'

2024-06-20 13:24 UTC, a-k-o-r-e-d-e commented on src/Pages/Homepage/Index.tsx
remove that console.log

2024-06-20 14:54 UTC, a-k-o-r-e-d-e commented
@demi05 also resolve the conflicts

2024-06-20 15:30 UTC, demi05 commented on src/Pages/Homepage/Index.tsx
done

2024-06-20 15:30 UTC, demi05 commented on src/Global Components/Logo/Logo.tsx
done

2024-06-20 15:41 UTC, a-k-o-r-e-d-e approved these changes

2024-06-20 15:41 UTC, merged