consumed the api for each school homepage and the list of quizes for the select quiz section
SkillsForge-Community/Sigma-Quiz-UI pull request #79
Opened 2024-06-24 15:09 UTC by silasade

2024-06-25 07:22 UTC, a-k-o-r-e-d-e requested changes
Also create a central point or file for your types and declare them there. so they can be reused

2024-06-25 07:22 UTC, a-k-o-r-e-d-e commented on package.json
you need two cookie packages?

2024-06-25 07:22 UTC, a-k-o-r-e-d-e commented on src/Global Components/Pagininate/Paginate1.tsx
whats Paginate1.tsx ? does that suggest there will be a Paginate2.tsx

Proper file and variable names are required

2024-06-25 07:22 UTC, a-k-o-r-e-d-e commented on src/Global Components/Pagininate/Paginate1.tsx
PaginatedItems1?? 

Nah, nah, i want proper file, variable and Class Names

2024-06-26 14:08 UTC, silasade commented on package.json
Uninstalled JS-COOKIE

2024-06-26 14:09 UTC, silasade commented on src/Global Components/Pagininate/Paginate1.tsx
Fixed the name.

2024-06-26 14:14 UTC, silasade commented on src/Global Components/Pagininate/Paginate1.tsx
It has been renamed

2024-06-26 14:56 UTC, a-k-o-r-e-d-e approved these changes

2024-06-26 14:56 UTC, merged