Consumed the mark question and assign bonus api
SkillsForge-Community/Sigma-Quiz-UI pull request #80
Opened 2024-06-27 22:09 UTC by silasade

2024-06-27 22:18 UTC, a-k-o-r-e-d-e requested changes

2024-06-27 22:18 UTC, a-k-o-r-e-d-e commented on src/Global Components/SchoolDetails/SchoolDetails.tsx
line 118 & 179, use the base url already declared

2024-06-27 22:18 UTC, a-k-o-r-e-d-e commented on src/Global Components/Types/Types.tsx
Probably not the best way to declare the types, but i will allow

2024-06-27 22:18 UTC, a-k-o-r-e-d-e commented on src/features/getQuestionID.tsx
why do you need a slicer to get question ID, just curious

2024-06-27 23:20 UTC, silasade commented on src/Global Components/SchoolDetails/SchoolDetails.tsx
This issue has been resolved.

2024-06-27 23:30 UTC, silasade commented on src/features/getQuestionID.tsx
I had to make sure the question id is visible in the parent component, I am open to better ways of solving it.

2024-06-27 23:40 UTC, silasade commented on src/Global Components/Types/Types.tsx
Already resolved it

2024-06-28 04:11 UTC, a-k-o-r-e-d-e approved these changes

2024-06-28 04:15 UTC, a-k-o-r-e-d-e commented on src/features/getQuestionID.tsx
There should be a simpler way of achieving the same thing but for the sake of speed. I will allow for now

2024-06-28 04:15 UTC, merged